### ISSUE TITLE
証明書の有効期限を変更したいのですが、ソースの変更箇所を教えていただけないでしょうか？

### ISSUE THREAD

**Issue by KatsujiYoshimura** [nifcloud/genca#1]
作成される証明書の有効期限を変更したいと思っております。
ソースの変更行および変更箇所をご教授いただけませんでしょうか？

また変更箇所を修正してコンパイルするだけで問題ないかも教えていただけますと幸いです。
以上、よろしくお願いいたします。

**Comment by hasunuma** [comment]
@KatsujiYoshimura issueありがとうございます。
証明書の有効期限ですが、デフォルトでは4年になっています。  
[こちら](https://github.com/nifcloud/genca/blob/master/genca.go#L239)の`years`の4を変更して頂ければ、サーバー証明書やクライアント証明書の有効期限が変更されます。  

CA証明書の有効期限については[genCACertの関数](https://github.com/nifcloud/genca/blob/master/genca.go#L351)で有効期限を指定しているため、この箇所を変更すれば任意の有効期限に変更可能です。  

ソースコードの変更後、[README](https://github.com/nifcloud/genca#%E3%82%BD%E3%83%BC%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%89%E3%81%AE%E3%83%93%E3%83%AB%E3%83%89)の通りbuildすれば任意の有効期限で証明書を生成するツールとして利用出来ると思います。(golangのパッケージインストールなどが必要です。)

* golang
```
# ubuntu 22.04 LTSの場合
root@ubuntu:~# apt-get update
root@ubuntu:~# apt-get install golang-go
root@ubuntu:~# go version
go version go1.18.1 linux/amd64

root@ubuntu:~# git clone https://github.com/nifcloud/genca.git
root@ubuntu:~# cd genca
root@ubuntu:~/genca# go build genca.go
root@ubuntu:~/genca# 
```
* gox
https://github.com/mitchellh/gox

**Comment by hasunuma** [comment]
追加コメントが無いので、こちらクローズさせて頂きます。
