### ISSUE TITLE
Windows11対応は今後検討されていますでしょうか

### ISSUE THREAD

**Issue by YuAsakawa** [nifcloud/genca#2]
本ツール、利用させていただいております。ありがとうございます。
Windows10に対応しているかと思いますが、
Windows11への対応は検討されていますでしょうか。

**Comment by hasunuma** [comment]
@YuAsakawa issueありがとうございます。
gencaのWindows11への対応ですが、 [v2.0](https://github.com/nifcloud/genca/releases/tag/2.0)の以下バイナリがWindows11 23H2で正常に動作する事を確認しています。

* genca_windows_386.exe

* genca_windows_amd64.exe

このため、現時点でgencaはWindows11に対応済みとなります。  
以上よろしくお願いします。

**Comment by hasunuma** [comment]
追加コメントが無いので、こちらクローズさせて頂きます。
