### ISSUE TITLE
client.nifcloud.local.pfxはインポート不要でしょうか？

### ISSUE THREAD

**Issue by ju-asao** [nifcloud/genca#3]
CA証明書を作成する際はclient.nifcloud.local.pfxを指定した手順がありますが、Genca V2.0では削除されています。
端末にインポートするファイルは不要でしょうか？Windows11 端末になります

**Comment by hasunuma** [comment]
@ju-asao issueありがとうございます。
> 端末にインポートするファイルは不要でしょうか？Windows11 端末になります

はい、ご認識の通りpfxファイルをWindows端末にimportする必要はなくなりました。  
v2.0.0以前まではクライアント証明書認証でpfxファイルのimportが必要でしたが、v2.0.0以降ではコントロールパネルよりダウンロード可能な `クライアント設定ファイル` 内にクライアント証明書認証に必要な情報を入力し、importする利用方法に変更となりました。

ご参考: [リモートアクセスVPNゲートウェイ：Windows 11のリモートアクセスVPNゲートウェイ(v2.0.0)利用方法](https://docs.nifcloud.com/network/guide/ravgwv2_setup_win11.htm)

このためgenca v2.0以降ではpfxファイルを出力する機能をなくしています。

**Comment by ju-asao** [comment]
@hasunuma 
承知しました。ありがとうございます。
